### ISSUE TITLE
[Bug] GitHub Action failure when creating new repo from template

### ISSUE THREAD

**Issue by gclhub** [skills/hello-github-actions#30] opened 2023-01-09 18:57 UTC
**Describe the bug**
I started the GitHub Actions skills course and began by creating my own repository from the skills repo template. During that process, a GitHub Action runs to set up the new repo. I saw the following failure that prevented the GH Action from creating a PR in my repo: https://github.com/gclhub/hello-github-actions/actions/runs/3876581724/jobs/6610590261

**To Reproduce**
Follow the steps outlined at https://github.com/skills/hello-github-actions#how-to-start-this-course

**Expected behavior**
The PR should be created successfully in the new repo created from the template.

**Comment by Audioyu** [comment] 2023-01-10 11:23
啊，这个问题我开始也遇到了；这样设置就可以解决：
![屏幕截图 2023-01-10 192134](https://user-images.githubusercontent.com/99396091/211538538-2ffc1e76-9382-4541-8a08-b87247c9a92a.png)

**Comment by Amigux** [comment] 2023-01-25 09:17
the problem is you can update these settings only after creating (forkin) the repo and at the creation the step 0 launch automatically and has no rights to create the pull request expected

**Comment by frank-leitner** [comment] 2023-02-06 22:46
Workaround: 

1. Manually delete the 'welcome-workflow' branch that was created during the fork
2. Perform the changes posted by @Audioyu 
3. Manually start the 'Step 0, Start' action

The remaining steps work again.

**Comment by sinsukehlab** [comment] 2023-02-10 10:16
The workflow `0-start.yml` in the course skills/release-based-workflow also creates a pull request but it runs without errors. The restriction can probably be circumvented by running shell scripts (`.github/script/*.sh`) instead of running commands directly coded in YAML files (`.github/workflows/*.yml`).

**Comment by ncalteen** [comment] 2023-02-10 15:15
Since creating a repository from a template does not copy the template's settings, another workaround would be to include instructions to:

1. Create an organization
2. Enable the **Read and write permissions** and **Allow GitHub Actions to create and approve pull requests** settings at the organization level
3. Copy the template repository into the organization

Alternatively, add a new workflow that is invoked before `.github/workflows/0-start.yml` that checks if GitHub Actions has the necessary permissions before attempting to create branches or PRs.

I'm happy to submit a PR to the template for either, but I'll defer to the owners for the approach they would like to take 😄

**Comment by chadfawcett** [comment] 2023-02-15 18:57
Hey all! This should now be resolved by https://github.com/skills/hello-github-actions/pull/36

**Closed by chadfawcett** 2023-02-15 18:57 UTC
Labels: bug
