### ISSUE TITLE
Can't make it past step 2

### ISSUE THREAD

**Issue by camihmerhar** [skills/hello-github-actions#62] opened 2024-01-25 17:00 UTC
### Summary

Hello! I work with @a-a-ron on the ACE team and we were getting told by our learners that they keep getting stalled at Step 2. I went and followed the steps and this happened to me as well. 

### How to reproduce

1. Complete step 1 of the [hello-git-hub-actions skill](https://github.com/skills/hello-github-actions)
2. Copy and paste content into welcome.yml file 

For reference [here's my repo](https://github.com/camibam/skills-hello-github-actions) if you wanna take a gander and ensure I followed the instructions properly. 

And a screen shot of my step 2 just incase it helps 
![Screenshot 2024-01-25 at 10 53 19 AM](https://github.com/skills/hello-github-actions/assets/112580737/fba7a7fa-d99e-4303-9a5d-e779c98082d9)

Let me know if there's anything I can help out with! 

Cheers,
Cami

**Comment by djthornton1212** [comment] 2024-02-11 20:42
@camihmerhar, going by your screenshot, it looks like you updated the wrong file. The instructions had you create `welcome.yml`, then continue updating it as the instructions progressed. 

From the looks of your screenshot, you updated the original  `0-welcome.yml` workflow the actions team created instead of the `welcome.yml` workflow you created in step 1. Note that in your branch the `welcome.yml` file doesn't have a jobs section:
<img width="387" alt="image" src="https://github.com/skills/hello-github-actions/assets/99346713/074c5542-be5c-4462-8a8f-67d7d0bb3ef3">

**Comment by hectorsector** [comment] 2024-02-12 16:01
👋 @camihmerhar thanks for the report! @djthornton1212's suggestions above are correct - if you're using the course for learners you might want to make it easier for them by letting them know they're supposed to update the `welcome.yml` file in their pull request or maybe including some troubleshooting steps. We also welcome PRs so if you think we can improve the instructions we're open to ideas. Since everything seems to be working as intended, I'm going to close this as not a bug but please reopen if you'd like to discuss further.

**Closed by hectorsector** 2024-02-12 16:01 UTC
Labels: bug
